services:
  l4d2:
    pull_policy: build
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_IMAGE: dsanc9996/l4d2-server-core:latest
        PLUGIN_IMAGE: dsanc9996/l4d2-plugin-pack:core
