services:
  l4d2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER_IMAGE: dsanc9996/l4docker:server-core
        PLUGIN_IMAGE: dsanc9996/l4docker:plugins-core
    image: dsanc9996/l4docker:standard
    network_mode: host
